DEBUG = 0

INCLUDE_EMPTY = False
DETECT_NEW_ITEMS = True
ALTERNATIVE_CHARS = True
MAX_LINE_Y_DIFF = 300
MIN_SCORE_MATCH = 0.3
# Larger values were causing issues
# https://trello.com/c/AcprXW31
MIN_NUMERIC_SCORE_MATCH = 0
MAX_DURATION = 16
MIN_LINE_HEIGHT = 20
MIN_WORD_SEPARATION = 20
WORD_SPLIT_DISTANCE = 30

USE_DEEP_LEARNING_HINTS = False
