# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 15:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import ocrapi.api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(max_length=128, verbose_name='Unique Identification of the user')),
                ('uploaded_at', models.DateTimeField(default=datetime.date.today)),
                ('url', models.ImageField(max_length=254, upload_to=ocrapi.api.models.get_file_path)),
                ('status', models.CharField(default='PENDING', max_length=10, verbose_name='Status of the analysis')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, verbose_name='Product description')),
                ('quantity', models.FloatField()),
                ('unit_price_pre_gst', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('price_pre_gst', models.FloatField()),
                ('price', models.FloatField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.AnalyzedImage')),
            ],
        ),
    ]
