# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_itemchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedimage',
            name='matching_order_id',
            field=models.CharField(max_length=254, null=True, verbose_name='Oder ID'),
        ),
    ]
