# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170313_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedimage',
            name='status',
            field=models.CharField(default='PENDING', max_length=25, verbose_name='Status of the analysis'),
        ),
    ]
