# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 18:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170313_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedimage',
            name='webhook_url',
            field=models.URLField(max_length=1000, null=True, verbose_name='webhook url'),
        ),
        migrations.AlterField(
            model_name='analyzedimage',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
