# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_analyzedimage_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedimage',
            name='wholesalers',
            field=models.TextField(null=True, verbose_name='available wholesalers products'),
        ),
    ]
