# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_analyzedimage_wholesalers'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='order_item_id',
            field=models.CharField(max_length=254, null=True, verbose_name='Order Item ID'),
        ),
    ]
