# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_item_order_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedimage',
            name='metrics',
            field=models.TextField(null=True, verbose_name='metrics computed on client'),
        ),
    ]
