# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_analyzedimage_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemchange',
            name='expected_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='itemchange',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
