# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 10:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import ocrapi.api.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170429_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(default=datetime.datetime.now)),
                ('url', models.ImageField(max_length=254, upload_to=ocrapi.api.models.get_file_path)),
                ('webhook_url', models.URLField(max_length=1000, null=True, verbose_name='webhook url')),
                ('status', models.CharField(default='PENDING', max_length=25, verbose_name='Status of the analysis')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.AnalyzedImage'),
        ),
        migrations.AddField(
            model_name='item',
            name='structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.Structure'),
        ),
    ]
