# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170713_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=100, null=True, verbose_name='Product code'),
        ),
    ]
