# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-13 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=1000, null=True, verbose_name='Product description'),
        ),
    ]
