# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-28 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import ocrapi.api.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20170713_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedimage',
            name='rotation',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='structure',
            name='url',
            field=models.FileField(max_length=254, upload_to=ocrapi.api.models.get_file_path),
        ),
    ]
