# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-30 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ocrapi.api.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20170828_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(max_length=254, upload_to=ocrapi.api.models.get_file_path)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='api.AnalyzedImage')),
                ('structure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='api.Structure')),
            ],
        ),
    ]
