# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-30 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='url',
        ),
    ]
