# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-01 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_structure_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='rotation',
            field=models.FloatField(default=0),
        ),
    ]
