# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-06 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20170905_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(max_length=100, null=True, verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='item',
            name='pack_size',
            field=models.CharField(max_length=100, null=True, verbose_name='Pack Size'),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_of_measure',
            field=models.CharField(max_length=100, null=True, verbose_name='Unit Of Measure'),
        ),
    ]
